### ISSUE TITLE
imagenet_train

### ISSUE THREAD

**Issue by GGboywxy** [xinwong/adversarial-detection#1]
Thank you for the code you've provided, but I've encountered issues when training a model on the ImageNet dataset. It seems that the code you've provided isn't complete. Could you please help clarify and resolve my doubts?

**Comment by xinwong** [comment]
The training stage follows the same process as demonstrated in the Adversarial Robustness Toolbox. See the example provided at: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/get_started_pytorch.py

**Comment by xinwong** [comment]
For ImageNet, we directly utilized a pre-trained model.
